### ISSUE TITLE
System.MissingMethodException on README example

### ISSUE THREAD

**Issue by johnW-ret** [plbonneville/BlazorInteractive#310]
Running the following commands in C# cells in VSCode results in the respectively displayed outputs:
```
#r "nuget: BlazorInteractive, 1.1.5"
```

> Installed Packages
> - BlazorInteractive, 1.1.5

```
#!blazor
<h1>Hello @name</h1>

@code {
    string name = "Alice";
}
```

<details open>

  <summary>click to collapse</summary>

  ```
Error: System.AggregateException: One or more errors occurred. (Method not found: 'Void Microsoft.DotNet.Interactive.Commands.SubmitCode..ctor(System.String, System.String, Microsoft.DotNet.Interactive.Commands.SubmissionType)'.)
---> System.MissingMethodException: Method not found: 'Void Microsoft.DotNet.Interactive.Commands.SubmitCode..ctor(System.String, System.String, Microsoft.DotNet.Interactive.Commands.SubmissionType)'.
at BlazorInteractive.BlazorExtensions.AddComponentTypeToInteractiveWorkspace(Kernel kernel, String code)
at BlazorInteractive.BlazorExtensions.<>c__DisplayClass0_1`1.<<UseBlazor>b__1>d.MoveNext()
--- End of inner exception stack trace ---
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
at System.Threading.Tasks.Task.Wait()
at BlazorInteractive.BlazorExtensions.<>c__DisplayClass0_0`1.<UseBlazor>b__0(BlazorMarkdown markdown, TextWriter writer)
at Microsoft.DotNet.Interactive.Formatting.Formatter.<>c__DisplayClass46_0`1.<Register>b__0(Object value, FormatContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive.Formatting\Formatter.cs:line 427
at Microsoft.DotNet.Interactive.Formatting.Formatter`1.FormatTo(T obj, FormatContext context, String mimeType) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive.Formatting\Formatter{T}.cs:line 79
at Microsoft.DotNet.Interactive.Formatting.Formatter.FormatTo[T](T obj, FormatContext context, String mimeType) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive.Formatting\Formatter.cs:line 320
at Microsoft.DotNet.Interactive.Formatting.Formatter.ToDisplayString(Object obj, String mimeType) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive.Formatting\Formatter.cs:line 277
at Microsoft.DotNet.Interactive.FormattedValue.<>c__DisplayClass12_0.<CreateManyFromObject>b__0(String mimeType) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\FormattedValue.cs:line 49
at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
at Microsoft.DotNet.Interactive.FormattedValue.CreateManyFromObject(Object value, String[] mimeTypes) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\FormattedValue.cs:line 47
at Microsoft.DotNet.Interactive.KernelInvocationContextExtensions.Display(KernelInvocationContext context, Object value, String[] mimeTypes) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelInvocationContextExtensions.cs:line 22
at BlazorInteractive.BlazorKernel.HandleAsync(SubmitCode command, KernelInvocationContext context)
at Microsoft.DotNet.Interactive.Kernel.<>c__DisplayClass82_0`1.<SetHandler>b__0(KernelCommand _, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Kernel.cs:line 874
at Microsoft.DotNet.Interactive.Commands.KernelCommand.InvokeAsync(KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Commands\KernelCommand.cs:line 187
at Microsoft.DotNet.Interactive.Kernel.HandleAsync(KernelCommand command, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Kernel.cs:line 330
at Microsoft.DotNet.Interactive.KernelCommandPipeline.<BuildPipeline>b__6_0(KernelCommand command, KernelInvocationContext context, KernelPipelineContinuation _) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 60
at Microsoft.DotNet.Interactive.KernelCommandPipeline.SendAsync(KernelCommand command, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 41
```

</details>

Results of `#!about`:

<details open>
   <summary>click to collapse</summary>

> .NET Interactive
> © 2020 Microsoft Corporation
> Version: 1.0.460602+802607e5de228b87f402de10321137d4d4f0cf81
> Library version: 1.0.0-beta.23606.2+802607e5de228b87f402de10321137d4d4f0cf81
> Build date: 2023-12-06T23:52:16.5952443Z
> https://github.com/dotnet/interactive
</details>

Environment.Version is `8.0.0`

**Comment by plbonneville** [comment]
Hi @johnW-ret, I've upgraded .NET from version 7.0 to 8.0. #311

The issue should be resolved with NuGet package version 1.2.0.

Do reach out if the problem continues.
